// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";

function getWaitTime(str) {
  let parse = (str, _counter) => {
    while (true) {
      let counter = _counter;
      let c = str[counter];
      if (c === undefined) {
        if (counter > 0) {
          return {
            TAG: "Ok",
            _0: [
              "m",
              counter
            ]
          };
        } else {
          return {
            TAG: "Error",
            _0: "Couldn't parse duration."
          };
        }
      }
      let match = Stdlib_Int.fromString(c, undefined);
      if (match === undefined) {
        if (counter > 0) {
          return {
            TAG: "Ok",
            _0: [
              c,
              counter
            ]
          };
        } else {
          return {
            TAG: "Error",
            _0: "Argument doesn't start with a number."
          };
        }
      }
      _counter = counter + 1 | 0;
      continue;
    };
  };
  let x = parse(str, 0);
  if (x.TAG !== "Ok") {
    return x;
  }
  let match = x._0;
  let units;
  switch (match[0]) {
    case "d" :
      units = "Days";
      break;
    case "h" :
      units = "Hours";
      break;
    case "m" :
      units = "Minutes";
      break;
    case "s" :
      units = "Seconds";
      break;
    default:
      units = "Unknown";
  }
  if (units === "Unknown") {
    return {
      TAG: "Error",
      _0: "Invalid duration. Only minutes, seconds, hours and days supported (singular letter only)."
    };
  }
  let slice = str.slice(0, match[1] + 1 | 0);
  let i = Stdlib_Int.fromString(slice, undefined);
  let num = i !== undefined ? ({
      TAG: "Ok",
      _0: i
    }) : ({
      TAG: "Error",
      _0: "Couldn't parse argument :( this probably shouldn't happen"
    });
  if (num.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: [
        units,
        num._0
      ]
    };
  } else {
    return num;
  }
}

async function executeReminder(timeType, duration, label) {
  let timeString;
  switch (timeType) {
    case "Seconds" :
      timeString = {
        TAG: "Ok",
        _0: "seconds"
      };
      break;
    case "Minutes" :
      timeString = {
        TAG: "Ok",
        _0: "minutes"
      };
      break;
    case "Hours" :
      timeString = {
        TAG: "Ok",
        _0: "hours"
      };
      break;
    case "Days" :
      timeString = {
        TAG: "Ok",
        _0: "days"
      };
      break;
    case "Unknown" :
      timeString = {
        TAG: "Error",
        _0: "Provided Unknown as time type"
      };
      break;
  }
  if (timeString.TAG !== "Ok") {
    return timeString;
  }
  let formatted = [
    "in",
    duration.toString(),
    timeString._0
  ];
  let formatted$1 = label !== undefined ? formatted.concat(label) : formatted;
  let reminder = await command.execute("remindme", ...formatted$1);
  if (reminder.success === true) {
    return {
      TAG: "Ok",
      _0: reminder.reply
    };
  } else {
    return {
      TAG: "Error",
      _0: reminder.reply
    };
  }
}

async function main(args) {
  let arg = args[0];
  if (arg === undefined) {
    return "Please provide arguments to this alias. Can be used like \"$$r 15\" (reminds you in 15 minutes if seconds not specified)";
  }
  let waitTime = getWaitTime(arg);
  let label = args.length === 1 ? undefined : args.slice(1);
  if (waitTime.TAG !== "Ok") {
    return waitTime._0;
  }
  let match = waitTime._0;
  let reminder = await executeReminder(match[0], match[1], label);
  if (reminder.TAG === "Ok") {
    return reminder._0;
  } else {
    return `Couldn't execute a reminder. Supibot error: ` + reminder._0;
  }
}

export {
  getWaitTime,
  executeReminder,
  main,
}
/* No side effect */
